# CONNECTIONS
listen_addresses = '*'
max_connections = 100

# MEMORY
shared_buffers = 256MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 768MB

# WAL / DURABILITY
wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB
checkpoint_completion_target = 0.9

# QUERY PLANNER
random_page_cost = 1.1
effective_io_concurrency = 200

# LOGGING
logging_collector = off
log_min_duration_statement = 200
log_statement = 'none'

# LOCALE
datestyle = 'iso, mdy'
timezone = 'UTC'
default_text_search_config = 'pg_catalog.english'
